### ISSUE TITLE
Metadata file format

### ISSUE THREAD

**Issue by MattiaBo** [camilla-ip/poreqc#1]
Hi Camilla!

I'm trying to run your poreqc script on MinION data but I don't understand how to compile the metadata file. Do you have any example of the format of the file?

Many thanks,
Mattia.

**Comment by camilla-ip** [comment]
Hi Mattia

I'm attaching a sample metadata.txt file. Please let me know if you have 
any further problems.

Cheers
Camilla

On 09/11/2015 09:45, MattiaBo wrote:
>
> Hi Camilla!
>
> I'm trying to run your poreqc script on MinION data but I don't 
> understand how to compile the metadata file. Do you have any example 
> of the format of the file?
>
> Many thanks,
> Mattia.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/camilla-ip/poreqc/issues/1>.
>


runstartdate,20150420
hostname,LAPTOP1
flowcellid,FAA31864
samplenameshort,expt1
outfileprefix,expt1
experimentname,expt1
experimentaims,
experimentdesc,
samplenamefull,
species,E. coli
chemistryversion,R7.3
programlength_hrs,48
minknowversion,UNKNOWN
maprefid,hg19
mindepthrequired,1

**Comment by MattiaBo** [comment]
Thank you Camilla, I will let you know!
